// Package protocol defines the wire types exchanged between the agent and
// the Agent Workflow Platform broker. This is the canonical Go implementation of Agent
// Protocol v1 wire types shared with the control-plane broker.
//
// Invariants:
//   - Envelope is the single on-the-wire shape. `Payload` is a json.RawMessage
//     so the framing layer can hand it to a typed unmarshaler once `Type` has
//     been dispatched.
//   - `ID` is a ULID (26 chars, Crockford base32) generated by
//     internal/ulid.New(). Monotonic within a process.
//   - `TS` is a unix seconds float (RFC-3339-compatible when serialized).
//     The spec is lenient about millisecond precision — we use float64 and
//     preserve micro precision via time.Time.UnixNano()/1e9.
//   - Unknown top-level fields MUST be preserved on forwarding. Since we
//     decode into a strict struct the forwarding concern is moot for the
//     agent (we always re-serialize our own frames), but the unmarshaller
//     MUST NOT fail on unknown fields in server frames.
//
// The file is big on purpose — per the spec, every frame type has a concrete
// Go struct so callers cannot mis-spell field names.
package protocol

import (
	"encoding/json"
	"errors"
	"fmt"
	"time"
)

// ProtocolVersion is the wire version. Bumped on any incompatible change.
const ProtocolVersion = 1

// Type enumerates envelope kinds. Values are the `type` JSON field.
type Type string

// Envelope types — keep alphabetically grouped by namespace for sanity.
const (
	// Handshake
	TypeHello   Type = "hello"
	TypeWelcome Type = "welcome"

	// Auth
	TypeAuthLogin    Type = "auth.login"
	TypeAuthSession  Type = "auth.session"
	TypeAuthRefresh  Type = "auth.refresh"
	TypeAuthExpiring Type = "auth.expiring"

	// Heartbeat / keepalive
	TypeHeartbeat Type = "heartbeat"
	TypePing      Type = "ping"
	TypePong      Type = "pong"

	// Task lifecycle
	TypeTaskOffer    Type = "task.offer"
	TypeTaskAccept   Type = "task.accept"
	TypeTaskReject   Type = "task.reject"
	TypeTaskProgress Type = "task.progress"
	TypeTaskComplete Type = "task.complete"
	TypeTaskCancel   Type = "task.cancel"
	TypeTaskResume   Type = "task.resume"
	TypeTaskOrphan   Type = "task.orphan"

	// Artifacts
	TypeArtifactRequestPut Type = "artifact.request_put"
	TypeArtifactPutURL     Type = "artifact.put_url"
	TypeArtifactUploaded   Type = "artifact.uploaded"

	// Logs / metrics
	TypeLogChunk       Type = "log.chunk"
	TypeMetricSnapshot Type = "metric.snapshot"

	// Control
	TypeControlDrain           Type = "control.drain"
	TypeControlUpgradeRequired Type = "control.upgrade_required"
	TypeControlCRL             Type = "control.crl"
	TypeControlShutdown        Type = "control.shutdown"

	// Flow-control protocol frames retained for compatible downstream brokers.
	// types_test.go and replay tests pin handling. The public control plane does
	// not emit these frames automatically.
	TypeFlowPause  Type = "flow.pause"
	TypeFlowResume Type = "flow.resume"

	// Ack / error / bye
	TypeAck Type = "ack"
	TypeBye Type = "bye"
	// TypeError is a fallback for code paths that haven't picked a specific
	// err.<category>.<specific> type. Real error frames are identified by
	// the `err.` prefix (see IsError). The spec uses err.* exclusively; this
	// constant exists only as a safety default when e.Code is empty.
	TypeError Type = "err.unknown.unspecified"
)

// IsError reports whether t is an error-namespace type (`err.*`).
func (t Type) IsError() bool {
	return len(t) >= 4 && t[:4] == "err."
}

// Envelope is the single frame shape on the wire.
//
// See spec §2.1.
type Envelope struct {
	V         int             `json:"v"`
	Type      Type            `json:"type"`
	ID        string          `json:"id"`
	InReplyTo string          `json:"in_reply_to,omitempty"`
	TS        float64         `json:"ts"`
	TraceID   string          `json:"trace_id,omitempty"`
	SpanID    string          `json:"span_id,omitempty"`
	Payload   json.RawMessage `json:"payload"`
}

// NowTS returns the current wall clock as a spec-compliant `ts` float.
func NowTS() float64 {
	return float64(time.Now().UnixNano()) / 1e9
}

// NewEnvelope packs a typed payload into a wire envelope.
// Caller supplies the frame ID (typically from ulid.New).
func NewEnvelope(id string, t Type, payload any) (*Envelope, error) {
	var raw json.RawMessage
	if payload != nil {
		b, err := json.Marshal(payload)
		if err != nil {
			return nil, fmt.Errorf("protocol: marshal payload for %s: %w", t, err)
		}
		raw = b
	} else {
		raw = json.RawMessage(`{}`)
	}
	return &Envelope{
		V:       ProtocolVersion,
		Type:    t,
		ID:      id,
		TS:      NowTS(),
		Payload: raw,
	}, nil
}

// MarshalEnvelope serializes an envelope to JSON bytes.
func MarshalEnvelope(e *Envelope) ([]byte, error) {
	if e == nil {
		return nil, errors.New("protocol: nil envelope")
	}
	if e.V == 0 {
		e.V = ProtocolVersion
	}
	if e.Payload == nil {
		e.Payload = json.RawMessage(`{}`)
	}
	return json.Marshal(e)
}

// UnmarshalEnvelope parses JSON bytes into an Envelope. Unknown fields are
// silently ignored (forward compatibility, spec §2.1 rule 4).
func UnmarshalEnvelope(b []byte) (*Envelope, error) {
	var e Envelope
	if err := json.Unmarshal(b, &e); err != nil {
		return nil, fmt.Errorf("protocol: decode envelope: %w", err)
	}
	if e.V != ProtocolVersion {
		// Not fatal on parse — the caller decides whether to negotiate, reject,
		// or log. We surface the raw envelope so the caller can inspect .V.
	}
	if e.Type == "" {
		return nil, errors.New("protocol: envelope missing type")
	}
	if e.ID == "" {
		return nil, errors.New("protocol: envelope missing id")
	}
	return &e, nil
}

// Decode unmarshals the envelope's payload into target v.
func (e *Envelope) Decode(v any) error {
	if len(e.Payload) == 0 {
		return errors.New("protocol: empty payload")
	}
	return json.Unmarshal(e.Payload, v)
}

// -----------------------------------------------------------------------------
// §3 Handshake payloads
// -----------------------------------------------------------------------------

// CPUInfo is the nested object inside HelloPayload.
type CPUInfo struct {
	Model   string `json:"model"`
	Cores   int    `json:"cores"`
	Threads int    `json:"threads"`
}

// HelloPayload — spec §3.2.
type HelloPayload struct {
	AgentID            string   `json:"agent_id"`
	AgentVersion       string   `json:"agent_version"`
	ProtocolVersions   []int    `json:"protocol_versions"`
	MinProtocolVersion int      `json:"min_protocol_version"`
	Distro             string   `json:"distro"`
	DistroID           string   `json:"distro_id"`
	DistroVersion      string   `json:"distro_version"`
	Kernel             string   `json:"kernel"`
	Arch               string   `json:"arch"`
	CPU                CPUInfo  `json:"cpu"`
	MemKB              int64    `json:"mem_kb"`
	RuntimeVersion     string   `json:"runtime_version"`
	RunnerVersion      string   `json:"runner_version"`
	RuntimeList        []string `json:"runtime_list"`
	Features           []string `json:"features"`
	Timezone           string   `json:"timezone"`
	BootID             string   `json:"boot_id"`
	StartTime          float64  `json:"start_time"`
}

// FeatureFlags — nested in WelcomePayload.
type FeatureFlags struct {
	MTLSRequired       bool     `json:"mtls_required"`
	ArtifactSignedURLs bool     `json:"artifact_signed_urls"`
	LogStreaming       bool     `json:"log_streaming"`
	MultiTask          bool     `json:"multi_task"`
	MaxConcurrentTasks int      `json:"max_concurrent_tasks"`
	Transport          []string `json:"transport"`
}

// WelcomePayload — spec §3.3.
type WelcomePayload struct {
	ServerVersion        string       `json:"server_version"`
	ProtocolVersion      int          `json:"protocol_version"`
	MinProtocolVersion   int          `json:"min_protocol_version"`
	RequiredAgentVersion string       `json:"required_agent_version"`
	SessionID            string       `json:"session_id"`
	SessionTTLSec        int          `json:"session_ttl_s"`
	FeatureFlags         FeatureFlags `json:"feature_flags"`
	HeartbeatIntervalSec int          `json:"heartbeat_interval_s"`
	HeartbeatGraceSec    int          `json:"heartbeat_grace_s"`
	ClockSkewMaxSec      int          `json:"clock_skew_max_s"`
}

// -----------------------------------------------------------------------------
// §4 Auth
// -----------------------------------------------------------------------------

type AuthLoginPayload struct {
	Method     string `json:"method"` // always "agent_token"
	AgentToken string `json:"agent_token"`
	AgentID    string `json:"agent_id"`
}

type AuthSessionPayload struct {
	BearerToken  string   `json:"bearer_token"`
	RefreshToken string   `json:"refresh_token"`
	NotAfter     float64  `json:"not_after"`
	TenantID     string   `json:"tenant_id"`
	AgentID      string   `json:"agent_id"`
	Scopes       []string `json:"scopes"`
}

type AuthRefreshPayload struct {
	RefreshToken string `json:"refresh_token"`
}

type AuthExpiringPayload struct {
	SecondsRemaining int `json:"seconds_remaining"`
}

// -----------------------------------------------------------------------------
// §5 Heartbeat
// -----------------------------------------------------------------------------

type LoadInfo struct {
	CPUPct        float64 `json:"cpu_pct"`
	MemUsedKB     int64   `json:"mem_used_kb"`
	MemTotalKB    int64   `json:"mem_total_kb"`
	DiskFreeKB    int64   `json:"disk_free_kb"`
	TaskSlotsFree int     `json:"task_slots_free"`
}

type HeartbeatPayload struct {
	RunningTaskIDs []string `json:"running_task_ids"`
	Load           LoadInfo `json:"load"`
	DrainRequested bool     `json:"drain_requested"`
	UptimeSec      float64  `json:"uptime_s"`
}

// -----------------------------------------------------------------------------
// §6 Task payloads
// -----------------------------------------------------------------------------

type ArtifactRef struct {
	URI             string  `json:"uri"`
	SHA256          string  `json:"sha256"`
	SizeBytes       int64   `json:"size_bytes"`
	ContentType     string  `json:"content_type,omitempty"`
	GetURL          string  `json:"get_url,omitempty"`
	GetURLExpiresAt float64 `json:"get_url_expires_at,omitempty"`
}

// InputSpec is polymorphic: either inline content or an artifact reference.
type InputSpec struct {
	Mode     string       `json:"mode"` // "inline" | "artifact"
	Inline   string       `json:"inline,omitempty"`
	Artifact *ArtifactRef `json:"artifact,omitempty"`
}

// ExecutionSpec describes a generic, allowlisted worker action.
type ExecutionSpec struct {
	Runner         string                 `json:"runner"`
	Runtime        string                 `json:"runtime,omitempty"`
	RuntimeVersion string                 `json:"runtime_version,omitempty"`
	Action         string                 `json:"action"`
	Outputs        []string               `json:"outputs,omitempty"`
	Parameters     map[string]interface{} `json:"parameters,omitempty"`
	Includes       []ArtifactRef          `json:"includes,omitempty"`
	Input          InputSpec              `json:"input"`
	Options        map[string]string      `json:"options,omitempty"`
}

type TaskConstraints struct {
	MinMemKB  int64 `json:"min_mem_kb,omitempty"`
	MinDiskKB int64 `json:"min_disk_kb,omitempty"`
}

type TaskTrace struct {
	TraceID      string `json:"trace_id"`
	ParentSpanID string `json:"parent_span_id"`
}

type TaskOfferPayload struct {
	TaskID         string          `json:"task_id"`
	IdempotencyKey string          `json:"idempotency_key"`
	TenantID       string          `json:"tenant_id"`
	Priority       int             `json:"priority"`
	SubmittedAt    float64         `json:"submitted_at"`
	TimeoutSec     int             `json:"timeout_s"`
	Execution      ExecutionSpec   `json:"execution"`
	Constraints    TaskConstraints `json:"constraints"`
	Trace          TaskTrace       `json:"trace"`
}

type TaskAcceptPayload struct {
	TaskID     string  `json:"task_id"`
	AcceptedAt float64 `json:"accepted_at"`
}

type TaskRejectPayload struct {
	TaskID      string  `json:"task_id"`
	Reason      string  `json:"reason"` // busy | unhealthy | incompatible_runtime | missing_feature | quota_exceeded
	RetryAfterS float64 `json:"retry_after_s,omitempty"`
	Detail      string  `json:"detail"`
}

type TaskProgressPayload struct {
	TaskID  string `json:"task_id"`
	Seq     int    `json:"seq"`
	Percent int    `json:"percent"`
	Phase   string `json:"phase"` // setup | running | post | upload
	Note    string `json:"note,omitempty"`
}

type TaskErrorDetail struct {
	Code      string                 `json:"code"`
	Message   string                 `json:"message"`
	Retryable bool                   `json:"retryable"`
	Details   map[string]interface{} `json:"details,omitempty"`
}

type TaskCompletePayload struct {
	TaskID      string                 `json:"task_id"`
	Status      string                 `json:"status"` // success | error | canceled
	Metrics     map[string]interface{} `json:"metrics"`
	DurationSec float64                `json:"duration_s"`
	Artifacts   []ArtifactRef          `json:"artifacts"`
	Error       *TaskErrorDetail       `json:"error,omitempty"`
	CompletedAt float64                `json:"completed_at"`
}

type TaskCancelPayload struct {
	TaskID string `json:"task_id"`
	Reason string `json:"reason"` // user_requested | timeout | quota | admin
	GraceS int    `json:"grace_s"`
}

type TaskResumePayload struct {
	TaskID string `json:"task_id"`
	SeqAck int    `json:"seq_ack"`
}

type TaskOrphanPayload struct {
	TaskID           string  `json:"task_id"`
	IdempotencyKey   string  `json:"idempotency_key"`
	Reason           string  `json:"reason"` // agent_restart | host_reboot | corruption
	LastKnownPercent float64 `json:"last_known_percent"`
}

// -----------------------------------------------------------------------------
// §7 Artifact payloads
// -----------------------------------------------------------------------------

type ArtifactRequestPutPayload struct {
	TaskID      string `json:"task_id"`
	Kind        string `json:"kind"`
	SizeBytes   int64  `json:"size_bytes"`
	SHA256      string `json:"sha256"`
	ContentType string `json:"content_type"`
}

type ArtifactPutURLPayload struct {
	TaskID    string            `json:"task_id"`
	Kind      string            `json:"kind"`
	URL       string            `json:"url"`
	Method    string            `json:"method"` // "PUT"
	Headers   map[string]string `json:"headers"`
	ExpiresAt float64           `json:"expires_at"`
}

type ArtifactUploadedPayload struct {
	TaskID    string `json:"task_id"`
	Kind      string `json:"kind"`
	URI       string `json:"uri"`
	SHA256    string `json:"sha256"`
	SizeBytes int64  `json:"size_bytes"`
	ETag      string `json:"etag"`
}

// -----------------------------------------------------------------------------
// §11 Logs / metrics
// -----------------------------------------------------------------------------

type LogChunkPayload struct {
	TaskID string   `json:"task_id"`
	Seq    int      `json:"seq"`
	Stream string   `json:"stream"` // stdout | stderr | awp
	Level  string   `json:"level"`  // DEBUG | INFO | WARN | ERROR
	TS     float64  `json:"ts"`
	Lines  []string `json:"lines"`
}

type MetricSnapshotPayload struct {
	TaskID  string                 `json:"task_id"`
	TS      float64                `json:"ts"`
	Metrics map[string]interface{} `json:"metrics"`
}

// -----------------------------------------------------------------------------
// §9 Control
// -----------------------------------------------------------------------------

type ControlDrainPayload struct {
	Reason   string  `json:"reason"`
	Deadline float64 `json:"deadline"`
}

type ControlUpgradeRequiredPayload struct {
	MinimumVersion string `json:"minimum_version"`
	LatestVersion  string `json:"latest_version"`
	DownloadURL    string `json:"download_url"`
	SHA256         string `json:"sha256"`
	Ed25519Sig     string `json:"ed25519_sig"`
	GraceSeconds   int    `json:"grace_seconds"`
}

type ControlCRLPayload struct {
	RevokedAgentTokens  []string `json:"revoked_agent_tokens"`
	RevokedClientCerts  []string `json:"revoked_client_certs"`
	RevokedBearerTokens []string `json:"revoked_bearer_tokens"`
	Generation          int      `json:"generation"`
	NotAfter            float64  `json:"not_after"`
}

type ControlShutdownPayload struct {
	Reason string `json:"reason"`
}

// -----------------------------------------------------------------------------
// Ack / Error / Bye
// -----------------------------------------------------------------------------

type AckPayload struct {
	ForID  string `json:"for_id"`
	Seq    int    `json:"seq,omitempty"`
	Window int    `json:"window,omitempty"`
}

type ErrorPayload struct {
	Code        string                 `json:"code"` // err.<category>.<specific>
	Message     string                 `json:"message"`
	Retryable   bool                   `json:"retryable"`
	RetryAfterS float64                `json:"retry_after_s,omitempty"`
	TaskID      string                 `json:"task_id,omitempty"`
	TraceID     string                 `json:"trace_id,omitempty"`
	Details     map[string]interface{} `json:"details,omitempty"`
}

type ByePayload struct {
	Reason string `json:"reason,omitempty"`
}
