<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'

import {
  configuredApiUrl,
  createControlPlaneClient,
  saveConnection,
} from '@/api/controlPlane'

defineProps<{
  theme: string
  toggleTheme: () => void
}>()

const router = useRouter()
const apiUrl = configuredApiUrl()
const devKey = ref('')
const revealKey = ref(false)
const loading = ref(false)
const error = ref<string | null>(null)

async function connect(): Promise<void> {
  error.value = null
  loading.value = true
  try {
    const cleanKey = devKey.value.trim()
    if (!cleanKey) throw new Error('Enter the development API key.')
    const client = createControlPlaneClient({ apiBase: apiUrl, devKey: cleanKey })
    await Promise.all([client.health(), client.tasks()])
    saveConnection(cleanKey)
    await router.replace({ name: 'dashboard' })
  } catch (caught) {
    error.value = caught instanceof Error ? caught.message : 'Could not connect.'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <main class="connect-page">
    <button class="theme-button" type="button" :aria-label="`Use ${theme === 'dark' ? 'light' : 'dark'} theme`" @click="toggleTheme">
      {{ theme === 'dark' ? 'Light mode' : 'Dark mode' }}
    </button>

    <section class="connect-card" aria-labelledby="connect-title">
      <div class="brand-mark" aria-hidden="true">AWP</div>
      <p class="eyebrow">LOCAL CONTROL PLANE</p>
      <h1 id="connect-title">Agent Workflow Platform</h1>
      <p class="intro">Connect the monitor to the local service. The first request checks readiness and verifies access to the task API.</p>

      <form @submit.prevent="connect">
        <label for="api-url">API endpoint</label>
        <input id="api-url" :value="apiUrl" type="url" readonly aria-describedby="api-help" />
        <p id="api-help" class="field-help">Set at build time with <code>VITE_AWP_API_URL</code>. Only loopback addresses are accepted.</p>

        <label for="dev-key">Development key</label>
        <div class="key-field">
          <input
            id="dev-key"
            v-model="devKey"
            :type="revealKey ? 'text' : 'password'"
            autocomplete="off"
            spellcheck="false"
          />
          <button type="button" class="reveal-button" @click="revealKey = !revealKey">
            {{ revealKey ? 'Hide' : 'Show' }}
          </button>
        </div>
        <p class="field-help">Paste the random key generated by the local Compose control plane. It remains in this browser session only.</p>

        <div v-if="error" class="error-box" role="alert">
          <strong>Connection failed</strong>
          <span>{{ error }}</span>
        </div>

        <button class="connect-button" type="submit" :disabled="loading || !devKey.trim()">
          <span v-if="loading" class="spinner" aria-hidden="true"></span>
          {{ loading ? 'Checking control plane…' : 'Open monitor' }}
        </button>
      </form>
    </section>
  </main>
</template>

<style scoped>
.connect-page {
  min-height: 100vh;
  display: grid;
  place-items: center;
  padding: 32px 20px;
  background:
    radial-gradient(circle at 15% 15%, var(--accent-glow), transparent 34%),
    radial-gradient(circle at 88% 82%, var(--success-glow), transparent 28%),
    var(--bg-primary);
}

.theme-button {
  position: fixed;
  top: 20px;
  right: 20px;
}

.connect-card {
  width: min(100%, 480px);
  padding: 38px;
  border: 1px solid var(--border);
  border-radius: 20px;
  background: var(--bg-panel);
  box-shadow: var(--shadow-lg);
}

.brand-mark {
  width: 52px;
  height: 52px;
  display: grid;
  place-items: center;
  border-radius: 15px;
  background: var(--accent);
  color: white;
  font-weight: 800;
  letter-spacing: -0.04em;
  box-shadow: 0 12px 30px var(--accent-shadow);
}

.eyebrow {
  margin-top: 24px;
  color: var(--accent);
  font-size: 11px;
  font-weight: 800;
  letter-spacing: 0.15em;
}

h1 {
  margin-top: 7px;
  font-size: clamp(26px, 6vw, 34px);
  letter-spacing: -0.04em;
}

.intro {
  margin: 10px 0 28px;
  color: var(--text-secondary);
  line-height: 1.65;
}

form {
  display: grid;
  gap: 9px;
}

label {
  margin-top: 8px;
  color: var(--text-primary);
  font-size: 12px;
  font-weight: 700;
}

input {
  width: 100%;
  min-height: 44px;
  padding: 0 13px;
  border: 1px solid var(--input-border);
  border-radius: 10px;
  background: var(--bg-surface);
  color: var(--text-primary);
  font: 500 13px var(--font-mono);
  outline: none;
}

input:focus {
  border-color: var(--accent);
  box-shadow: 0 0 0 3px var(--accent-dim);
}

input[readonly] {
  color: var(--text-secondary);
}

.key-field {
  position: relative;
}

.key-field input {
  padding-right: 66px;
}

.reveal-button {
  position: absolute;
  top: 6px;
  right: 6px;
  min-height: 32px;
  padding: 0 10px;
  border: 0;
  border-radius: 7px;
  background: var(--bg-hover);
  color: var(--text-secondary);
  cursor: pointer;
}

.field-help {
  margin-bottom: 5px;
  color: var(--text-muted);
  font-size: 11px;
  line-height: 1.5;
}

.error-box {
  display: grid;
  gap: 2px;
  margin-top: 8px;
  padding: 12px 14px;
  border: 1px solid var(--danger-border);
  border-radius: 10px;
  background: var(--danger-bg);
  color: var(--danger);
  font-size: 12px;
}

.connect-button {
  min-height: 46px;
  margin-top: 12px;
  border: 0;
  border-radius: 11px;
  background: var(--accent);
  color: white;
  font-weight: 750;
  cursor: pointer;
}

.connect-button:hover:not(:disabled) { background: var(--accent-hover); }
.connect-button:disabled { cursor: not-allowed; opacity: 0.58; }

.spinner {
  display: inline-block;
  width: 14px;
  height: 14px;
  margin-right: 7px;
  border: 2px solid rgb(255 255 255 / 35%);
  border-top-color: white;
  border-radius: 50%;
  vertical-align: -2px;
  animation: spin 0.8s linear infinite;
}

@keyframes spin { to { transform: rotate(360deg); } }

@media (max-width: 520px) {
  .connect-card { padding: 28px 22px; }
}
</style>
