import { defineConfig } from '@playwright/test'

const electronSpecs = [
  'activity-events-api.spec.ts',
  'activity-sidebar-toggle.spec.ts',
  'agent-status-snapshot-schema.spec.ts',
  'artifacts-dispatcher-api.spec.ts',
  'auth-lifecycle-api.spec.ts',
  'cc-cli-local-phase2.spec.ts',
  'cc-wrapper-lifecycle.spec.ts',
  'chat-history-crud-api.spec.ts',
  'chat-models-list-api.spec.ts',
  'chat-sse.spec.ts',
  'check-for-updates.spec.ts',
  'connection-status-dot-states.spec.ts',
  'connection-status-dot-unknown.spec.ts',
  'conversation-management.spec.ts',
  'failimg-switch-bypass.spec.ts',
  'health-public-probes-api.spec.ts',
  'legal-links.spec.ts',
  'login.spec.ts',
  'logout-double-click.spec.ts',
  'logout-regression.spec.ts',
  'notifications-ui.spec.ts',
  'onboarding-flow.spec.ts',
  'resources-usage-api.spec.ts',
  'sessions-lifecycle-api.spec.ts',
  'settings-server-url.spec.ts',
  'sidebar-collapse-persist.spec.ts',
  'sidebar-newthread-kbd.spec.ts',
  'sse-reconnection-recovery.spec.ts',
  'support-diagnostic-upload-ui.spec.ts',
  'user-profile-ui.spec.ts',
]

export default defineConfig({
  testDir: './e2e',
  testMatch: electronSpecs,
  timeout: 120_000,
  expect: { timeout: 15_000 },
  fullyParallel: false,
  workers: 1,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  reporter: process.env.CI ? [['list'], ['html', { open: 'never' }]] : [['list']],
  use: {
    screenshot: 'only-on-failure',
    trace: 'on-first-retry',
    video: 'retain-on-failure',
  },
})